Compress interface tables with packed encoding
tanishiking/scala-wasm pull request #121
Opened 2024-05-06 10:38 UTC by tanishiking

This commit implements the "packed encoding" algorithm for compressing interface tables (itables). The algorithm is based on the paper "Efficient Type Inclusion Tests". https://www.researchgate.net/publication/2438441_Efficient_Type_Inclusion_Tests It compresses the itable by reusing itable indices for unrelated types, reducing the size of the itable array. For scalajs-test-suite, the itable size is reduced from 413 to 47.

This change didn't reduce the size of wasm binary that much (14957kb to 14943kb), but it should be space efficient.

We chose packed encoding because the compression rate is good enough among the presented methods in the paper. While hierarchical encoding is slightly better compression rate, packed encoding is better in both compile-time and runtime performance in CPU and space.

2024-05-06 13:12 UTC, sjrd requested changes

2024-05-06 13:12 UTC, sjrd commented on wasm/src/main/scala/wasm4s/WasmContext.scala
> +    _buckets = assignBuckets0(classes)
Perhaps immediately filter out all classes that are `.kind.isJSType`. It is a bit hard to reason about what the algorithm will do with JS types, as is, but in fact it shouldn't do anything at all.

2024-05-07 03:28 UTC, tanishiking commented on wasm/src/main/scala/wasm4s/WasmContext.scala
> +    val idx = buckets.indexWhere(b => b.elements.contains(iface))
Thanks! Right, as a consequence of storing the `itableIdx` to its `ClassInfo` (+ changes around start function), we no longer need to store the `buckets` in `WasmContext` :+1:

2024-05-07 03:29 UTC, tanishiking commented on wasm/src/main/scala/wasm4s/WasmContext.scala
> +      new mutable.LinkedHashMap[IRNames.ClassName, mutable.LinkedHashSet[IRNames.ClassName]]()
Right, thanks!

2024-05-07 03:32 UTC, tanishiking commented on wasm/src/main/scala/wasm4s/WasmContext.scala
> +      (if (clazz.kind == ClassKind.Interface) List(className) else Nil) ++
Oh, I misunderstood something, indeed we don't need this

2024-05-07 05:12 UTC, sjrd approved these changes

2024-05-07 05:12 UTC, merged