Add const string to data section
tanishiking/scala-wasm pull request #63
Opened 2024-04-04 04:58 UTC by tanishiking

fix https://github.com/tanishiking/scala-wasm/issues/18

- Add a passive data segment that stores the concatenated string (encoded in UTF-16LE)
  -  `(data $string___data "\6e\00\61\00..."))`
- `getConstantStringInstr` call a `stringLiteral` helper function
- `stringLiteral` helper function does
  - Check if the string literal is found in a global cache (`array of anyref`)
  - if not found, gen i16 array using `array.new_data` and construct JS string using `createStringFromData` helper function, and cache it.

2024-04-04 04:59 UTC, tanishiking commented on package-lock.json
> +  "name": "scala-wasm",
Oops, my local repository was names `wasm4s` for no reason, and I just renamed it to `scala-wasm` that matches with the remote repo 😅

2024-04-04 08:19 UTC, sjrd requested changes
Looks good overall. Just one issue for strings that cannot be encoded in UTF-16 per se.

2024-04-05 08:52 UTC, sjrd approved these changes

2024-04-05 08:52 UTC, sjrd commented on wasm/src/main/scala/wasm4s/WasmContext.scala
> +    }
You made things difficult for yourself, but OK. I'm pretty sure this is equivalent to
```scala
val result = input.toCharArray()
```

2024-04-05 08:56 UTC, sjrd commented
GitHub seems to be a bit down. Actions in particular face "Major issues": https://www.githubstatus.com/

2024-04-05 09:02 UTC, sjrd commented
I think you'll need to force-push/rebase to try and get GitHub Actions to notice this PR again. It worked on some other PRs.

2024-04-05 13:58 UTC, sjrd commented
I took the liberty to rebase and address the trivial conflict.

2024-04-05 13:58 UTC, merged